name: New

on:
  # Run the workflow every 5 minutes
  # schedule:
  #   - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:
  


jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run some scheduled task
        run: |
          echo "This is a scheduled run every 5 minutes."
          # Your actual commands can go here, like tests, builds, etc.
